name: Tourism Project Pipeline

on:
  push:
    branches:
      - main

jobs:

  register-dataset:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Upload Dataset to Hugging Face Hub
        env:
          HF_TOKEN: ${{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}}
          HF_DATASET_ID: ${{Sarathbtech/visit-with-us-tourisms}}
        run: |
          python tourism_project1/model_building/data_registration.py

  data-prep:
    needs: register-dataset
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Data Preparation
        env:
          HF_TOKEN: ${{hf_hf_oNbtQQMdxENcjmkbaojXvAkQEqAGNpxeYf}}
          HF_DATASET_ID: ${{Sarathbtech/visit-with-us-tourisms}}
        run: |
          python tourism_project1/model_building/data_preparation.py

  model-traning:
    needs: data-prep
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Start MLflow Server
        run: |
          nohup mlflow ui --host 0.0.0.0 --port 5000 &
          sleep 10
      - name: Model Building
        env:
          HF_TOKEN: ${{hf_hf_oNbtQQMdxENcjmkbaojXvAkQEqAGNpxeYf}}
          HF_DATASET_ID: ${{Sarathbtech/visit-with-us-tourisms}}
          MLFLOW_TRACKING_URI: http://127.0.0.1:5000
        run: |
          python tourism_project1/model_building/model_training.py

  deploy-hosting:
    runs-on: ubuntu-latest
    needs: [model-traning, data-prep, register-dataset]
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Push files to Frontend Hugging Face Space
        env:
          HF_TOKEN: ${{hf_hf_oNbtQQMdxENcjmkbaojXvAkQEqAGNpxeYf}}
          HF_SPACE_ID: ${{Sarathbtech/visit-with-us-tourism-apps}}
        run: |
          python tourism_project1/deployment/push_to_hf_space.py
